services:
  homeassistant:
    image: ghcr.io/home-assistant/raspberrypi4-homeassistant:2024.9.3
    restart: unless-stopped
    env_file:
      - "./docker/homeassistant/homeassistant.env"
    volumes:
      - "./volumes/homeassistant/config:/config"
      - "./volumes/homeassistant/docker/run:/etc/services.d/home-assistant/run"
    privileged: true
    network_mode: host

  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.28.1
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "4443:4443"
      - "1744:1744"
      - "5900:5900"
    env_file:
      - "./docker/deconz/deconz.env"
    volumes:
      - "./volumes/deconz:/opt/deCONZ"
    networks:
     - "iotnet"

  mosquitto:
    build:
      context: ./docker/mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    env_file:
      - "./docker/mosquitto/mosquitto.env"
    volumes:
      - type: bind
        source: "./docker/mosquitto/mosquitto.conf"
        target: "/mosquitto/config/mosquitto.conf"
        read_only: true
      - "./volumes/mosquitto/data:/mosquitto/data"
      - "./volumes/mosquitto/log:/mosquitto/log"
    networks:
     - "iotnet"

  node-red:
    build:
      context: ./docker/nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    env_file:
      - "./docker/nodered/nodered.env"
    volumes:
      - "./volumes/nodered/data:/data"
    networks:
      - "iotnet"

  influx:
    image: influxdb:2.7.10
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - "./docker/influxdb/influxdb.env"
    volumes:
      - "./volumes/influxdb2/data:/var/lib/influxdb2"
      - "./volumes/influxdb2/config:/etc/influxdb2"
      - "./backups/influxdb2/db:/var/lib/influxdb2/backup"
    networks:
       - "iotnet"

  grafana:
    image: grafana/grafana:11.2.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - "./docker/grafana/grafana.env"
    volumes:
      - "./volumes/grafana/data:/var/lib/grafana"
      - "./volumes/grafana/log:/var/log/grafana"
    networks:
      - "iotnet"

  dockge:
    image: louislam/dockge:1.4.2
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./volumes/dockge/data:/app/data"
      - "./volumes/dockge/stacks:/opt/stacks"

networks:
  iotnet:
    driver: bridge
