version: '3.7'

services:
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:2023.6.3
    restart: unless-stopped
    env_file:
      - "./docker/homeassistant/homeassistant.env"
    volumes:
      - "./volumes/homeassistant/config:/config"
      - "./volumes/homeassistant/docker/run:/etc/services.d/home-assistant/run"
    privileged: true
    network_mode: host

  deconz:
    image: deconzcommunity/deconz:2.23.00
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "4443:4443"
      - "1744:1744"
      - "5900:5900"
    env_file:
      - "./docker/deconz/deconz.env"
    volumes:
      - "./volumes/deconz:/opt/deCONZ"
    networks:
     - "iotnet"

  mosquitto:
    build:
      context: ./docker/mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    env_file:
      - "./docker/mosquitto/mosquitto.env"
    volumes:
      - type: bind
        source: "./docker/mosquitto/mosquitto.conf"
        target: "/mosquitto/config/mosquitto.conf"
        read_only: true
      - "./volumes/mosquitto/data:/mosquitto/data"
      - "./volumes/mosquitto/log:/mosquitto/log"
    networks:
     - "iotnet"

  node-red:
    build:
      context: ./docker/nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    env_file:
      - "./docker/nodered/nodered.env"
    volumes:
      - "./volumes/nodered/data:/data"
    networks:
      - "iotnet"

  influx:
    image: influxdb:1.8.10
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - "./docker/influxdb/influxdb.env"
    volumes:
      # - "./volumes/influxdb/data:/var/lib/influxdb2"
      # - "./volumes/influxdb/config:/etc/influxdb2"
      # - "./backups/influxdb/db:/var/lib/influxdb2/backup"
      - "./volumes/influxdb/data:/var/lib/influxdb"
      - "./backups/influxdb/db:/var/lib/influxdb/backup"
    networks:
       - "iotnet"

  grafana:
    image: grafana/grafana:9.5.8
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - "./docker/grafana/grafana.env"
    volumes:
      - "./volumes/grafana/data:/var/lib/grafana"
      - "./volumes/grafana/log:/var/log/grafana"
    networks:
      - "iotnet"

networks:
  iotnet:
    driver: bridge
