services:
  grafana:
    image: grafana/grafana:11.2.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - "./docker/grafana.env"
    volumes:
      - "./volume/data:/var/lib/grafana"
      - "./volume/log:/var/log/grafana"
    networks:
      - "iotnet"

networks:
  iotnet:
    driver: bridge
    name: iotnet_network