services:
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.28.1
    restart: unless-stopped
    container_name: deconz
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 4443:4443
      - 1744:1744
      - 5900:5900
    env_file:
      - ./docker/deconz.env
    volumes:
      - ./volume:/opt/deCONZ
    networks:
     - iotnet

networks:
  iotnet:
    driver: bridge
    name: iotnet_network
