services:
  dockge:
    image: louislam/dockge:1.4.2
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./volume/data:/app/data"
      - "../services:/app/services"
    environment:
      - DOCKGE_STACKS_DIR=/app/services

networks:
  iotnet:
    driver: bridge
