services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.11.3
    restart: unless-stopped
    container_name: homeassistant
    env_file:
      - ./docker/homeassistant.env
    volumes:
      - ./volume/config:/config
      - ./volume/docker/run:/etc/services.d/home-assistant/run
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
